# Basic Mathematics for AI

This notebook follows the main ideas in the presentation and gives a **simple explanation** for each topic, followed by **brief Python code**.

The goal is not to be exhaustive, but to provide a compact computational companion to the slides.

---

## Contents

1. Scalars, vectors, matrices, and tensors  
2. Matrix-vector and matrix-matrix multiplication  
3. Matrices as linear transformations  
4. Identity and inverse matrices  
5. Linear systems, dependence, and span  
6. Special kinds of matrices  
7. Dot product  
8. Inner product  
9. Norms and $L^p$ norms  
10. $L^2$, $L^1$, and other norms  
11. Eigenvalues and eigenvectors  
12. Eigendecomposition  
13. Singular Value Decomposition (SVD)  
14. Derivative  
15. Gradient and directional derivative  
16. Chain rule  
17. Jacobian  
18. Hessian  
19. Taylor approximation  
20. Convexity


## Basics: Linear Algebra for AI

In [34]:
import numpy as np

### 1. Scalars, vectors, matrices, and tensors

A **scalar** is a single number.  
A **vector** is an ordered list of numbers.  
A **matrix** is a rectangular array of numbers.  
A **tensor** is a multidimensional array.

In AI:
- scalars can represent a loss value,
- vectors can represent features or embeddings,
- matrices can represent weight layers,
- tensors can represent batches of images, sequences, or activations.


In [35]:
scalar = 3.14
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])
tensor = np.arange(24).reshape(2, 3, 4)

print("Scalar:", scalar)
print("Vector shape:", vector.shape)
print("Matrix shape:", matrix.shape)
print("Tensor shape:", tensor.shape)


Scalar: 3.14
Vector shape: (3,)
Matrix shape: (2, 2)
Tensor shape: (2, 3, 4)


### 2. Matrix-vector and matrix-matrix multiplication

If $A \in \mathbb{R}^{m \times n}$ and $\mathbf{x} \in \mathbb{R}^n$, then $A\mathbf{x} \in \mathbb{R}^m$.

If $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$, then $AB \in \mathbb{R}^{m \times p}$.

In machine learning, matrix-vector multiplication appears in the forward pass of linear layers.


In [36]:
A = np.array([[1, 2],
              [3, 4]])
x = np.array([1, -1])
B = np.array([[2, 0],
              [1, 5]])

print("A @ x =", A @ x)
print("A @ B =\n", A @ B)


A @ x = [-1 -1]
A @ B =
 [[ 4 10]
 [10 20]]


### 3. Matrices as linear transformations

A matrix can be viewed as a transformation that sends an input vector to an output vector.

Examples:
- scaling,
- rotation,
- reflection,
- projection.

This viewpoint is very useful in AI because weight matrices transform feature vectors into new representations.


In [37]:
theta = np.pi / 6  # 30 degrees
R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

v = np.array([1.0, 0.0])
Rv = R @ v

print("Original vector:", v)
print("Rotated vector:", Rv)


Original vector: [1. 0.]
Rotated vector: [0.8660254 0.5      ]


### 4. Identity and inverse matrices

The **identity matrix** leaves vectors unchanged:
$ I\mathbf{x} = \mathbf{x} $.

If $A$ is invertible, then there exists $A^{-1}$ such that
$ AA^{-1} = A^{-1}A = I $.

In practice, we often solve linear systems instead of explicitly computing inverses.


In [38]:
A = np.array([[2.0, 1.0],
              [1.0, 1.0]])
I = np.eye(2)
A_inv = np.linalg.inv(A)

print("I =\n", I)
print("A^{-1} =\n", A_inv)
print("A @ A^{-1} =\n", A @ A_inv)


I =
 [[1. 0.]
 [0. 1.]]
A^{-1} =
 [[ 1. -1.]
 [-1.  2.]]
A @ A^{-1} =
 [[1. 0.]
 [0. 1.]]


### 5. Linear systems, dependence, and span

A **linear system** has the form $A\mathbf{x} = \mathbf{b}$.

Vectors are **linearly dependent** if one can be written as a combination of the others.

The **span** of vectors is the set of all linear combinations of them.

In AI, span and dependence matter in embeddings, feature spaces, and dimensionality reduction.


In [39]:
x1 = np.array([1, 2, 3])
x2 = np.array([2, 4, 6])
x3 = np.array([1, 0, 1])

print("x2 == 2*x1 ?", np.allclose(x2, 2*x1))

A = np.column_stack([x1, x3])
coeffs = np.array([3, -1])
y = A @ coeffs

print("A =\n", A)
print("Example vector in the span:", y)


x2 == 2*x1 ? True
A =
 [[1 1]
 [2 0]
 [3 1]]
Example vector in the span: [2 6 8]


### 6. Special kinds of matrices

Some important classes of matrices:
- **diagonal**: only diagonal entries may be nonzero,
- **symmetric**: $A = A^T$,
- **orthogonal**: $Q^TQ = I$.

Symmetric matrices appear in covariance matrices and Hessians. Orthogonal matrices preserve lengths and angles.


In [40]:
D = np.diag([1, 2, 3])
S = np.array([[2, 1],
              [1, 2]])
Q = np.array([[0, -1],
              [1,  0]])  # rotation by 90°

print("Diagonal matrix D =\n", D)
print("S symmetric? ", np.allclose(S, S.T))
print("Q orthogonal? ", np.allclose(Q.T @ Q, np.eye(2)))


Diagonal matrix D =
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
S symmetric?  True
Q orthogonal?  True


### 7. Dot product

For vectors $\mathbf{u}, \mathbf{v} \in \mathbb{R}^n$, the dot product is

$ \mathbf{u} \cdot \mathbf{v} = \sum_i u_i v_i $.

It measures alignment between vectors and is used in similarity scores and attention mechanisms.


In [41]:
u = np.array([1, 3, -5])
v = np.array([4, -2, -1])

dot = u @ v
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_alpha = dot / (norm_u * norm_v)

print("u · v =", dot)
print("||u|| =", norm_u)
print("||v|| =", norm_v)
print("cos(alpha) =", cos_alpha)


u · v = 3
||u|| = 5.916079783099616
||v|| = 4.58257569495584
cos(alpha) = 0.11065666703449763


### 8. Inner product

An **inner product** generalizes the dot product. In finite-dimensional Euclidean space, the standard inner product is just the dot product.

For functions, one common inner product is

$ \displaystyle \langle u, v \rangle = \int_\Omega u(x)v(x)\,dx $.

This idea appears in functional analysis, kernels, and continuous models.


In [42]:
x = np.linspace(0, 1, 1000)
u = x
v = x**2

inner_product = np.trapz(u * v, x)
print("Approximate function inner product <u,v> =", inner_product)


Approximate function inner product <u,v> = 0.250000250500751


### 9. Norms and $L^p$ norms

A **norm** measures the size of a vector.

For $p \ge 1$, the $L^p$ norm is

$\displaystyle \|\mathbf{x}\|_p = \left(\sum_i |x_i|^p\right)^{1/p} $.

Norms are used in regularization, optimization, and distance calculations.


In [43]:
x = np.array([1.0, -2.0, 3.0])

for p in [1, 2, 3]:
    val = np.sum(np.abs(x)**p)**(1/p)
    print(f"L^{p} norm =", val)


L^1 norm = 6.0
L^2 norm = 3.7416573867739413
L^3 norm = 3.3019272488946263


### 10. $L^2$, $L^1$, and other norms

- The **$L^2$ norm** is the Euclidean norm.
- The **$L^1$ norm** sums absolute values and is linked to sparsity.
- The **$L^\infty$ norm** takes the largest absolute entry.
- The **Frobenius norm** extends $L^2$-type measurement to matrices.


In [44]:
x = np.array([1.0, -2.0, 3.0])
A = np.array([[1, 2],
              [3, 4]])

l1 = np.linalg.norm(x, 1)
l2 = np.linalg.norm(x, 2)
linf = np.linalg.norm(x, np.inf)
fro = np.linalg.norm(A, "fro")

print("L1 norm =", l1)
print("L2 norm =", l2)
print("L-infinity norm =", linf)
print("Frobenius norm =", fro)


L1 norm = 6.0
L2 norm = 3.7416573867739413
L-infinity norm = 3.0
Frobenius norm = 5.477225575051661


### 11. Eigenvalues and eigenvectors

An eigenvector of a matrix $A$ is a nonzero vector $\mathbf{x}$ such that

$ A\mathbf{x} = \lambda \mathbf{x} $.

The vector keeps its direction up to scaling, and $\lambda$ is the scaling factor.

Eigenvalues and eigenvectors are central in PCA and covariance analysis.


In [45]:
A = np.array([[2, 1],
              [1, 2]])

eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues:", eigvals)
print("Eigenvectors (columns):\n", eigvecs)


Eigenvalues: [3. 1.]
Eigenvectors (columns):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### 12. Eigendecomposition

If a matrix has enough linearly independent eigenvectors, it can be decomposed as

$ A = Q\Lambda Q^{-1} $,

where $Q$ contains eigenvectors and $\Lambda$ contains eigenvalues.

For symmetric matrices, the decomposition is especially nice because $Q$ can be orthogonal.


In [46]:
A = np.array([[2, 1],
              [1, 2]])

eigvals, Q = np.linalg.eig(A)
Lambda = np.diag(eigvals)
A_reconstructed = Q @ Lambda @ np.linalg.inv(Q)

print("Q =\n", Q)
print("Lambda =\n", Lambda)
print("Q Lambda Q^{-1} =\n", A_reconstructed)


Q =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Lambda =
 [[3. 0.]
 [0. 1.]]
Q Lambda Q^{-1} =
 [[2. 1.]
 [1. 2.]]


### 13. Singular Value Decomposition (SVD)

Any matrix $A$ can be written as

$ A = U\Sigma V^T $.

SVD is fundamental in:
- dimensionality reduction,
- compression,
- recommender systems,
- numerical stability,
- PCA-related computations.


In [47]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=float)

U, s, VT = np.linalg.svd(A, full_matrices=False)
Sigma = np.diag(s)
A_reconstructed = U @ Sigma @ VT

print("Singular values:", s)
print("U =\n", U)
print("Sigma =\n", Sigma)
print("V^T =\n", VT)
print("Reconstruction error =", np.linalg.norm(A - A_reconstructed))


Singular values: [9.52551809 0.51430058]
U =
 [[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]
Sigma =
 [[9.52551809 0.        ]
 [0.         0.51430058]]
V^T =
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Reconstruction error = 1.3911054626160788e-15


## Basics: Analysis for Optimization

In [48]:
import numpy as np
import sympy as sp

### 14. Derivative

The derivative measures the instantaneous rate of change of a function and gives the best local linear approximation.

For a function $f(x)$, the derivative at $x_0$ is

$\displaystyle  f'(x_0) = \lim_{h\to 0} \frac{f(x_0+h)-f(x_0)}{h} $.


In [49]:
# ======================================================
# Function
# ======================================================

def f(x):
    return np.log(1 + np.exp(2*x))

# Point where we evaluate the derivative
x0 = 0.5

# ======================================================
# 1. Numerical derivative (finite differences)
# ======================================================

h = 1e-5
numerical_derivative = (f(x0 + h) - f(x0)) / h

# ======================================================
# 2. Exact derivative written by hand
# ======================================================

exact_derivative = 2*np.exp(2*x0) / (1 + np.exp(2*x0))

# ======================================================
# 3. Symbolic derivative with SymPy
# ======================================================

x = sp.symbols('x')
f_sym = sp.log(1 + sp.exp(2*x))

df_sym = sp.diff(f_sym, x)             # symbolic derivative
df_sym_simplified = sp.simplify(df_sym)

df_sym_func = sp.lambdify(x, df_sym_simplified, "numpy")
symbolic_derivative = df_sym_func(x0)

# ======================================================
# Results
# ======================================================

print("Function:")
print("f(x) = log(1 + exp(2x))")
print()

print("Symbolic derivative:")
print(df_sym_simplified)
print()

print("Numerical derivative:", numerical_derivative)
print("Exact derivative:    ", exact_derivative)
print("Symbolic derivative: ", symbolic_derivative)
print()

print("Error (numerical vs exact):   ", abs(numerical_derivative - exact_derivative))
print("Error (symbolic vs exact):    ", abs(symbolic_derivative - exact_derivative))

Function:
f(x) = log(1 + exp(2x))

Symbolic derivative:
2*exp(2*x)/(exp(2*x) + 1)

Numerical derivative: 1.4621210894905088
Exact derivative:     1.4621171572600098
Symbolic derivative:  1.4621171572600098

Error (numerical vs exact):    3.93223049899305e-06
Error (symbolic vs exact):     0.0


### 15. Gradient and directional derivative

For a scalar function of several variables, the **gradient** collects all first partial derivatives.

The gradient points in the direction of steepest ascent, so $-\nabla f$ gives a basic descent direction.

The **directional derivative** measures the rate of change along a chosen direction.


In [50]:
# ======================================================
# Function definition
# ======================================================

# Function: f(x,y) = x^2 + y^2 + xy
def f(x, y):
    return x**2 + y**2 + x*y


# ======================================================
# 1. Manual gradient (as in the slides)
# ======================================================

def grad_f(x, y):
    return np.array([2*x + y, x + 2*y])


# ======================================================
# Evaluation point and direction
# ======================================================

point = np.array([1.0, 2.0])

u = np.array([1.0, -1.0])
u = u / np.linalg.norm(u)   # normalize direction


# Manual gradient
g_manual = grad_f(*point)

# Directional derivative
directional_manual = g_manual @ u


# ======================================================
# 2. Symbolic gradient with SymPy
# ======================================================

x, y = sp.symbols('x y')

f_sym = x**2 + y**2 + x*y

grad_sym = sp.Matrix([
    sp.diff(f_sym, x),
    sp.diff(f_sym, y)
])

print("Symbolic gradient:")
sp.pprint(grad_sym)


# Convert symbolic gradient to numerical function
grad_func = sp.lambdify((x, y), grad_sym, "numpy")

g_symbolic = np.array(grad_func(*point), dtype=float).flatten()

directional_symbolic = g_symbolic @ u


# ======================================================
# Results
# ======================================================

print("\nPoint:", point)
print("Direction u:", u)

print("\nManual gradient:", g_manual)
print("Symbolic gradient:", g_symbolic)

print("\nManual directional derivative:", directional_manual)
print("Symbolic directional derivative:", directional_symbolic)

Symbolic gradient:
⎡2⋅x + y⎤
⎢       ⎥
⎣x + 2⋅y⎦

Point: [1. 2.]
Direction u: [ 0.70710678 -0.70710678]

Manual gradient: [4. 5.]
Symbolic gradient: [4. 5.]

Manual directional derivative: -0.7071067811865475
Symbolic directional derivative: -0.7071067811865475


### 16. Chain rule

The chain rule differentiates compositions.

If $y = f(u)$ and $u = g(x)$, then

$ \displaystyle \frac{dy}{dx} = \frac{dy}{du}\frac{du}{dx} $.

In deep learning, backpropagation is repeated application of the chain rule.

**Example**

Consider

$ f(u) = \ln(u) $
and
$ g(x) = x^2 + 3x + 1 $.

Then the composition is

$ y(x) = f(g(x)) = \ln(x^2 + 3x + 1) $.

By the chain rule,

$ y'(x) = f'(g(x))\,g'(x) $.

Since

$ \displaystyle f'(u) = \frac{1}{u} $ 
and 
$ g'(x) = 2x + 3 $,

we obtain

$ \displaystyle y'(x) = \frac{1}{x^2 + 3x + 1}(2x + 3) = \frac{2x + 3}{x^2 + 3x + 1} $.


In [51]:
# ======================================================
# Define the functions
# ======================================================

def g(x):
    return x**2 + 3*x + 1

def f(u):
    return np.log(u)

def composed(x):
    return f(g(x))


# ======================================================
# 1. Derivative using the chain rule (manual)
# ======================================================

x_val = 1.0

chain_rule_value = (1 / g(x_val)) * (2*x_val + 3)

print("Manual chain rule derivative:", chain_rule_value)


# ======================================================
# 2. Symbolic computation with SymPy
# ======================================================

x = sp.symbols('x')

g_sym = x**2 + 3*x + 1
f_sym = sp.log(g_sym)

df_sym = sp.diff(f_sym, x)
df_sym = sp.simplify(df_sym)

print("\nSymbolic derivative:")
sp.pprint(df_sym)


# ======================================================
# 3. Evaluate symbolic derivative
# ======================================================

df_func = sp.lambdify(x, df_sym, "numpy")

symbolic_value = df_func(x_val)

print("\nSymbolic derivative at x =", x_val, ":", symbolic_value)


# ======================================================
# 4. Compare both results
# ======================================================

print("\nDifference:", abs(symbolic_value - chain_rule_value))

Manual chain rule derivative: 1.0

Symbolic derivative:
  2⋅x + 3   
────────────
 2          
x  + 3⋅x + 1

Symbolic derivative at x = 1.0 : 1.0

Difference: 0.0


### 17. Jacobian

The **Jacobian matrix** is the matrix of first derivatives of a vector-valued function.

It describes the best local linear approximation of that function.


In [52]:
# ======================================================
# Vector function
# ======================================================

def F(x, y):
    return np.array([x**2 * y, np.sin(x*y)])

# Manual Jacobian (from the slides)
def jacobian_F(x, y):
    return np.array([
        [2*x*y, x**2],
        [y*np.cos(x*y), x*np.cos(x*y)]
    ])


# ======================================================
# Evaluation point
# ======================================================

x_val, y_val = 1.0, 2.0

print("Vector function value:")
print("F(x,y) =", F(x_val, y_val))

print("\nManual Jacobian:")
print(jacobian_F(x_val, y_val))


# ======================================================
# Symbolic Jacobian with SymPy
# ======================================================

x, y = sp.symbols('x y')

F_sym = sp.Matrix([
    x**2 * y,
    sp.sin(x*y)
])

J_sym = F_sym.jacobian([x, y])

print("\nSymbolic Jacobian:")
sp.pprint(J_sym)


# Convert symbolic Jacobian to numerical function
J_func = sp.lambdify((x, y), J_sym, "numpy")

J_symbolic = np.array(J_func(x_val, y_val), dtype=float)

print("\nSymbolic Jacobian evaluated at the point:")
print(J_symbolic)


# ======================================================
# Comparison
# ======================================================

print("\nDifference between manual and symbolic Jacobian:")
print(jacobian_F(x_val, y_val) - J_symbolic)

Vector function value:
F(x,y) = [2.         0.90929743]

Manual Jacobian:
[[ 4.          1.        ]
 [-0.83229367 -0.41614684]]

Symbolic Jacobian:
⎡                 2    ⎤
⎢  2⋅x⋅y         x     ⎥
⎢                      ⎥
⎣y⋅cos(x⋅y)  x⋅cos(x⋅y)⎦

Symbolic Jacobian evaluated at the point:
[[ 4.          1.        ]
 [-0.83229367 -0.41614684]]

Difference between manual and symbolic Jacobian:
[[0. 0.]
 [0. 0.]]


### 18. Hessian

The **Hessian** is the matrix of second derivatives of a scalar function.

It describes curvature and is very important in optimization.


In [53]:
# ======================================================
# Function
# ======================================================

# f(x,y,z) = x^2 + y^2 + z^2 + xy + xz

# Manual Hessian (from the lecture slides)
def hessian_example():
    return np.array([
        [2, 1, 1],
        [1, 2, 0],
        [1, 0, 2]
    ])

H_manual = hessian_example()

print("Manual Hessian:")
print(H_manual)

print("\nIs the Hessian symmetric?")
print(np.allclose(H_manual, H_manual.T))


# ======================================================
# Symbolic computation with SymPy
# ======================================================

x, y, z = sp.symbols('x y z')

f = x**2 + y**2 + z**2 + x*y + x*z

# Compute Hessian symbolically
H_sym = sp.hessian(f, (x, y, z))

print("\nSymbolic Hessian:")
sp.pprint(H_sym)


# Convert symbolic matrix to numerical numpy array
H_symbolic = np.array(H_sym, dtype=float)

print("\nSymbolic Hessian as numpy array:")
print(H_symbolic)


# ======================================================
# Comparison
# ======================================================

print("\nDifference between manual and symbolic Hessian:")
print(H_manual - H_symbolic)

Manual Hessian:
[[2 1 1]
 [1 2 0]
 [1 0 2]]

Is the Hessian symmetric?
True

Symbolic Hessian:
⎡2  1  1⎤
⎢       ⎥
⎢1  2  0⎥
⎢       ⎥
⎣1  0  2⎦

Symbolic Hessian as numpy array:
[[2. 1. 1.]
 [1. 2. 0.]
 [1. 0. 2.]]

Difference between manual and symbolic Hessian:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 19. Taylor approximation

Taylor polynomials approximate a function locally around a point.

For example, around $x_0=1$,

$ e^{5(x-1)} \approx 1 + 5(x-1) + \frac{25}{2}(x-1)^2 + \frac{125}{6}(x-1)^3 $.


In [54]:
# ======================================================
# Function
# ======================================================
def f(x):
    return np.exp(5*(x-1))


# ======================================================
# 1. Manual Taylor polynomial (order 3 around x0 = 1)
# ======================================================
def P3_manual(x):
    return 1 + 5*(x-1) + (25/2)*(x-1)**2 + (125/6)*(x-1)**3


# ======================================================
# 2. Symbolic Taylor polynomial with SymPy
# ======================================================

x = sp.symbols('x')

f_sym = sp.exp(5*(x-1))

P3_sym = sp.series(f_sym, x, 1, 4).removeO()

print("Symbolic Taylor polynomial:")
sp.pprint(P3_sym)


# Convert symbolic polynomial to numerical function
P3_sym_func = sp.lambdify(x, P3_sym, "numpy")


# ======================================================
# 3. Evaluation point
# ======================================================

x_val = 1.1

true_value = f(x_val)

manual_value = P3_manual(x_val)

symbolic_value = P3_sym_func(x_val)


# ======================================================
# 4. Results
# ======================================================

print("\nEvaluation at x =", x_val)

print("\nTrue value:")
print(true_value)

print("\nManual Taylor approximation:")
print(manual_value)

print("\nSymbolic Taylor approximation:")
print(symbolic_value)

print("\nManual absolute error:")
print(abs(true_value - manual_value))

print("\nSymbolic absolute error:")
print(abs(true_value - symbolic_value))

Symbolic Taylor polynomial:
                 3             2    
      125⋅(x - 1)    25⋅(x - 1)     
5⋅x + ──────────── + ─────────── - 4
           6              2         

Evaluation at x = 1.1

True value:
1.6487212707001289

Manual Taylor approximation:
1.6458333333333341

Symbolic Taylor approximation:
1.645833333333333

Manual absolute error:
0.002887937366794713

Symbolic absolute error:
0.002887937366795823


### 20. Convexity

A function is **convex** if the segment joining two points on its graph lies above the graph.

A key optimization fact is:

- for a convex function, every local minimum is also a global minimum.


In [55]:
def f(x):
    return x**2

x = -1.0
y = 2.0
lam = 0.3

left = f(lam*x + (1-lam)*y)
right = lam*f(x) + (1-lam)*f(y)

print("f(lambda x + (1-lambda) y) =", left)
print("lambda f(x) + (1-lambda) f(y) =", right)
print("Convexity inequality satisfied?", left <= right)


f(lambda x + (1-lambda) y) = 1.2099999999999997
lambda f(x) + (1-lambda) f(y) = 3.0999999999999996
Convexity inequality satisfied? True


## Exercises — Linear Algebra for AI


In [ ]:
import numpy as np
import sympy as sp

### Exercise A1 — Matrix-vector multiplication

Let

$$
A=
\begin{bmatrix}
2 & -1\\
1 & 3
\end{bmatrix},
\qquad
\mathbf{x}=
\begin{bmatrix}
4\\
2
\end{bmatrix}.
$$

Compute $A\mathbf{x}$.

**Solution idea.** Multiply each row of $A$ by the vector $\mathbf{x}$.


In [56]:
# write your code here


A x = [ 6 10]


### Exercise A2 — Dot product and angle

Let

$$
\mathbf{u}=
\begin{bmatrix}
1\\
2\\
2
\end{bmatrix},
\qquad
\mathbf{v}=
\begin{bmatrix}
2\\
1\\
2
\end{bmatrix}.
$$

Compute:
- the dot product $\mathbf{u}\cdot\mathbf{v}$,
- the norms \(\|\mathbf{u}\|_2$ and \(\|\mathbf{v}\|_2$,
- the cosine of the angle between them.

**Solution idea.** Use

$$
\cos\alpha=\frac{\mathbf{u}\cdot\mathbf{v}}{\|\mathbf{u}\|_2\|\mathbf{v}\|_2}.
$$


In [57]:
# write your code here


u · v = 8.0
||u|| = 3.0
||v|| = 3.0
cos(alpha) = 0.8888888888888888


### Exercise A3 — Linear dependence

Consider the vectors

$$
\mathbf{x}_1=
\begin{bmatrix}
1\\
0\\
1
\end{bmatrix},
\qquad
\mathbf{x}_2=
\begin{bmatrix}
2\\
0\\
2
\end{bmatrix},
\qquad
\mathbf{x}_3=
\begin{bmatrix}
0\\
1\\
1
\end{bmatrix}.
$$

Decide whether the set \(\{\mathbf{x}_1,\mathbf{x}_2,\mathbf{x}_3\}$ is linearly dependent.

**Solution idea.** Check whether one vector is a scalar multiple of another, or compute the rank of the matrix having these vectors as columns.


In [58]:
# write your code here


Matrix with vectors as columns:
[[1 2 0]
 [0 0 1]
 [1 2 1]]
Rank = 2
Number of vectors = 3
The vectors are linearly dependent.


### Exercise A4 — Norms of a vector

Let

$$
\mathbf{x}=
\begin{bmatrix}
1\\
-2\\
3
\end{bmatrix}.
$$

Compute:
- the $L^1$ norm,
- the $L^2$ norm,
- the $L^{\infty}$ norm.

**Solution idea.** Use the definitions of the norms directly.


In [59]:
# write your code here


L1 norm = 6.0
L2 norm = 3.7416573867739413
L-infinity norm = 3.0


### Exercise A5 — Eigenvalues and eigenvectors

Let

$$
B=
\begin{bmatrix}
3 & 1\\
1 & 3
\end{bmatrix}.
$$

Compute the eigenvalues and eigenvectors of $B$.

**Solution idea.** Since $B$ is symmetric, its eigenvalues are real and its eigenvectors can be chosen orthogonal.


In [60]:
# write your code here


Eigenvalues:
[4. 2.]

Eigenvectors (columns):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Exercises — Analysis for Optimization


### Exercise B1 — Derivative of a scalar function

Let

$$
f(x)=x^3+2x^2-x.
$$

Compute $f'(x)$ and evaluate it at $x=2$.

**Solution idea.** Differentiate term by term.


In [61]:
# write your code here


f'(x) = 3*x**2 + 4*x - 1
f'(2) = 19


### Exercise B2 — Gradient at a point

Let

$$
f(x,y)=x^2+y^2+xy.
$$

Compute the gradient $\nabla f(x,y)$ and evaluate it at the point $(1,2)$.

**Solution idea.** Compute the two partial derivatives and group them into a vector.


In [62]:
# write your code here


Gradient:
⎡2⋅x + y⎤
⎢       ⎥
⎣x + 2⋅y⎦

Gradient at (1,2):
⎡4⎤
⎢ ⎥
⎣5⎦


### Exercise B3 — Directional derivative

Let

$$
f(x,y)=x^2+y^2+xy,
\qquad
\mathbf{u}=\frac{1}{\sqrt{2}}
\begin{bmatrix}
1\\
-1
\end{bmatrix}.
$$

Compute the directional derivative $D_{\mathbf{u}}f(1,2)$.

**Solution idea.** Use

$$
D_{\mathbf{u}}f(\mathbf{x})=\nabla f(\mathbf{x})^\top \mathbf{u}.
$$


In [63]:
# write your code here


Gradient at point: [4. 5.]
Direction u: [ 0.70710678 -0.70710678]
Directional derivative: -0.7071067811865475


### Exercise B4 — Jacobian of a vector-valued function

Let

$$
\mathbf{F}(x,y)=
\begin{bmatrix}
x^2+y\\
xy
\end{bmatrix}.
$$

Compute the Jacobian matrix $J_{\mathbf{F}}(x,y)$ and evaluate it at $(1,2)$.

**Solution idea.** Differentiate each component of $\mathbf{F}$ with respect to each variable.


In [64]:
# write your code here


Jacobian:
⎡2⋅x  1⎤
⎢      ⎥
⎣ y   x⎦

Jacobian at (1,2):
⎡2  1⎤
⎢    ⎥
⎣2  1⎦


### Exercise B5 — Taylor polynomial of order 2

Let

$$
f(x)=e^x.
$$

Find the Taylor polynomial of order $2$ around $x_0=0$.

**Solution idea.** Use

$$
P_2(x)=f(0)+f'(0)x+\frac{f''(0)}{2}x^2.
$$


In [65]:
# write your code here


Taylor polynomial of order 2 around x0=0:
 2        
x         
── + x + 1
2         
